#!/usr/bin/env python
from athstmt import *
from athinterpreter import TildeAthInterp

stmts = AthStatementList([
    TildeAthLoop(False, AthStatementList([
        AthTokenStatement('input', [IdentifierToken('CARDSTR'), LiteralToken('Enter the shorthand string for your card, ex. 5H, 10S, QD: ', str)]),
        AthTokenStatement('ENUMERATE', [IdentifierToken('CARDSTR'), IdentifierToken('CARD')]),
        AthTokenStatement('REPLICATE', [IdentifierToken('TEMP'), IdentifierToken('CARD')]),
        AthTokenStatement('PROCREATE', [IdentifierToken('CARDLEN'), LiteralToken(0, int)]),
        AthTokenStatement('PROCREATE', [IdentifierToken('SUIT'), None]),
        TildeAthLoop(False, AthStatementList([
            AthTokenStatement('BIFURCATE', [IdentifierToken('TEMP'), IdentifierToken('LVAL'), IdentifierToken('TEMP')]),
            AthTokenStatement('PROCREATE', [IdentifierToken('CARDLEN'), BnaryExpr(['+', IdentifierToken('CARDLEN'), LiteralToken(1, int)])]),
            AthTokenStatement('PROCREATE', [IdentifierToken('SUIT'), IdentifierToken('LVAL')]),
            ], pendant='TEMP'),
            AthTokenStatement('EXECUTE', [IdentifierToken('NULL')])),
        AthTokenStatement('BIFURCATE', [IdentifierToken('CARD'), IdentifierToken('FACE'), IdentifierToken('NULL')]),
        CondiJump([BnaryExpr(['l|', BnaryExpr(['<', IdentifierToken('CARDLEN'), LiteralToken(2, int)]), BnaryExpr(['>', IdentifierToken('CARDLEN'), LiteralToken(3, int)])]), 2]),
        AthTokenStatement('print', [LiteralToken("That doesn't even LOOK like a card string!\\n", str)]),
        CondiJump([None, 59]),
        CondiJump([BnaryExpr(['==', IdentifierToken('CARDLEN'), LiteralToken(3, int)]), 2]),
        AthTokenStatement('PROCREATE', [IdentifierToken('FACENAME'), LiteralToken('Ten', str)]),
        CondiJump([None, 38]),
        CondiJump([BnaryExpr(['==', IdentifierToken('FACE'), LiteralToken('2', str)]), 2]),
        AthTokenStatement('PROCREATE', [IdentifierToken('FACENAME'), LiteralToken('Two', str)]),
        CondiJump([None, 35]),
        CondiJump([BnaryExpr(['==', IdentifierToken('FACE'), LiteralToken('3', str)]), 2]),
        AthTokenStatement('PROCREATE', [IdentifierToken('FACENAME'), LiteralToken('Three', str)]),
        CondiJump([None, 32]),
        CondiJump([BnaryExpr(['==', IdentifierToken('FACE'), LiteralToken('4', str)]), 2]),
        AthTokenStatement('PROCREATE', [IdentifierToken('FACENAME'), LiteralToken('Four', str)]),
        CondiJump([None, 29]),
        CondiJump([BnaryExpr(['==', IdentifierToken('FACE'), LiteralToken('5', str)]), 2]),
        AthTokenStatement('PROCREATE', [IdentifierToken('FACENAME'), LiteralToken('Five', str)]),
        CondiJump([None, 26]),
        CondiJump([BnaryExpr(['==', IdentifierToken('FACE'), LiteralToken('6', str)]), 2]),
        AthTokenStatement('PROCREATE', [IdentifierToken('FACENAME'), LiteralToken('Six', str)]),
        CondiJump([None, 23]),
        CondiJump([BnaryExpr(['==', IdentifierToken('FACE'), LiteralToken('7', str)]), 2]),
        AthTokenStatement('PROCREATE', [IdentifierToken('FACENAME'), LiteralToken('Seven', str)]),
        CondiJump([None, 20]),
        CondiJump([BnaryExpr(['==', IdentifierToken('FACE'), LiteralToken('8', str)]), 2]),
        AthTokenStatement('PROCREATE', [IdentifierToken('FACENAME'), LiteralToken('Eight', str)]),
        CondiJump([None, 17]),
        CondiJump([BnaryExpr(['==', IdentifierToken('FACE'), LiteralToken('9', str)]), 2]),
        AthTokenStatement('PROCREATE', [IdentifierToken('FACENAME'), LiteralToken('Nine', str)]),
        CondiJump([None, 14]),
        CondiJump([BnaryExpr(['==', IdentifierToken('FACE'), LiteralToken('J', str)]), 2]),
        AthTokenStatement('PROCREATE', [IdentifierToken('FACENAME'), LiteralToken('Jack', str)]),
        CondiJump([None, 11]),
        CondiJump([BnaryExpr(['==', IdentifierToken('FACE'), LiteralToken('Q', str)]), 2]),
        AthTokenStatement('PROCREATE', [IdentifierToken('FACENAME'), LiteralToken('Queen', str)]),
        CondiJump([None, 8]),
        CondiJump([BnaryExpr(['==', IdentifierToken('FACE'), LiteralToken('K', str)]), 2]),
        AthTokenStatement('PROCREATE', [IdentifierToken('FACENAME'), LiteralToken('King', str)]),
        CondiJump([None, 5]),
        CondiJump([BnaryExpr(['==', IdentifierToken('FACE'), LiteralToken('A', str)]), 2]),
        AthTokenStatement('PROCREATE', [IdentifierToken('FACENAME'), LiteralToken('Ace', str)]),
        CondiJump([None, 2]),
        AthTokenStatement('PROCREATE', [IdentifierToken('FACENAME'), LiteralToken('WRONG', str)]),
        AthTokenStatement('print', [LiteralToken("This isn't a real card face!\\n", str)]),
        CondiJump([BnaryExpr(['==', IdentifierToken('SUIT'), LiteralToken('S', str)]), 2]),
        AthTokenStatement('PROCREATE', [IdentifierToken('SUITNAME'), LiteralToken('Spade', str)]),
        CondiJump([None, 11]),
        CondiJump([BnaryExpr(['==', IdentifierToken('SUIT'), LiteralToken('H', str)]), 2]),
        AthTokenStatement('PROCREATE', [IdentifierToken('SUITNAME'), LiteralToken('Heart', str)]),
        CondiJump([None, 8]),
        CondiJump([BnaryExpr(['==', IdentifierToken('SUIT'), LiteralToken('D', str)]), 2]),
        AthTokenStatement('PROCREATE', [IdentifierToken('SUITNAME'), LiteralToken('Diamond', str)]),
        CondiJump([None, 5]),
        CondiJump([BnaryExpr(['==', IdentifierToken('SUIT'), LiteralToken('C', str)]), 2]),
        AthTokenStatement('PROCREATE', [IdentifierToken('SUITNAME'), LiteralToken('Club', str)]),
        CondiJump([None, 2]),
        AthTokenStatement('PROCREATE', [IdentifierToken('SUITNAME'), LiteralToken('WRONG', str)]),
        AthTokenStatement('print', [LiteralToken("This isn't a real card suit!\\n", str)]),
        CondiJump([BnaryExpr(['l|', BnaryExpr(['==', IdentifierToken('SUITNAME'), LiteralToken('WRONG', str)]), BnaryExpr(['==', IdentifierToken('FACENAME'), LiteralToken('WRONG', str)])]), 2]),
        AthTokenStatement('print', [LiteralToken('Go back and try again with a REAL deck of cards!\\n', str)]),
        CondiJump([None, 1]),
        AthTokenStatement('print', [LiteralToken('Your card is the ~s of ~ss.\\n', str), IdentifierToken('FACENAME'), IdentifierToken('SUITNAME')]),
        AthTokenStatement('DIE', [IdentifierToken('THIS')]),
        ], pendant='THIS'),
        AthTokenStatement('EXECUTE', [IdentifierToken('NULL')]))
    ], pendant='THIS')

if __name__ == '__main__':
    TildeAthInterp().exec_stmts('CardParser.~ATH', stmts)
